services:
  music-bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: wekkly-music-dorm-bot
    restart: unless-stopped
    env_file: .env.bot
    volumes:
      - ./data:/app/data
      - ../discord-dorm-bot/database/requester-names:/app/dorm-users:ro
